# 📊 Getting locations

**Objective:** Get location data and create a .csv

**Data Source:** listado_escuelas_primaria_arequipa.csv, listado_escuelas_secundaria_arequipa.csv & listado_escuelas_primaria_y_secundaria_arequipa.csv

**Output:**

### Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from dbfread import DBF

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)
pd.set_option('display.float_format', '{:.2f}'.format)

### Paths

In [38]:
# Entradas
listado_escuelas_primaria_y_secundaria_arequipa = "../../data/cleaned/listado_escuelas_primaria_y_secundaria_arequipa.csv"

# Salidas
PATH_OUT_FULL    = '../../data/cleaned/districts.csv'

### Data Loading

In [13]:
# --- Opción A: CSV ---
df_p_s = pd.read_csv(listado_escuelas_primaria_y_secundaria_arequipa)
# --- Opción B: DBF ---
# from dbfread import DBF
# df_a = pd.DataFrame(iter(DBF(PATH_RAW_A, encoding='cp1252')))
# df_b = pd.DataFrame(iter(DBF(PATH_RAW_B, encoding='utf-8')))

# --- Opción C: Excel ---
# df_a = pd.read_excel(PATH_RAW_A, sheet_name=0)

### Data Inspection

In [14]:
df_p_s.describe(include='all')

,COD_MOD,ANEXO,CODLOCAL,NROCED,CEN_EDU,DISTRITO,LOCALIDAD,P104A,P105A,P105A_S_1,P105A_S_2,P105A_S_3,P105A_S_4,P105A_S_5,P105A_S_5O,P106A,P107A,P107A_NO,P107A_NO_O,P108A,P109A_1,P109A_2,P109A_3,P109A_4,P109A_5,P109A_6,P110A,P111A_1,P111A_2,P111A_3,P111A_4,P111A_5,P111A_6,P111A_5_OT,P112A,P112A_SI,P113A,P113A_S_1,P113A_S_2,P113A_S_3,P113A_S_4,P113A_S_5,P113A_S_6,P113A_S_6O,P114A,P114A_S_1,P114A_S_2,P114A_S_3,P114A_S_4,P114A_S_5,P114A_S_5O,P116A,P117A,P117A_1_CP,P117A_2_CP,P118A,P118A_S_1,P118A_S_2,P118A_S_3,P118A_S_4,P118A_S_5,P118A_S_5O,P119A,P120A,P121A,P122A,P122A_S_1,P122A_S_2,P122A_S_3,P122A_S_4,P122A_S_5,P122A_S_5O,P123A,P123A_SI,P102B_1,P102B_2,P102B_3,P102B_4,P102B_5,P102B_6,P102B_7,P102B_8,P102B_8_OT,P103B,P103B_SI_1,P103B_SI_2,P105B,P106B,P106B_SI,P109B_1,P109B_2,P109B_3,P109B_4,P109B_5,P109B_6,P109B_7,P109B_7_OT,P110B_1,P110B_2,P110B_3,P110B_4,P111B,P112B,P112B_SI,P113B,P113B_SI,P114B_1,P114B_2,P114B_3,P114B_4,P114B_5,P114B_6,P114B_7,P114B_8,P114B_8_OT,P115B_1,P115B_2,P115B_3,P115B_4,P115B_5,P115B_6,P115B_7,P115B_6_OT,P117B,P118B,P118B_SI,P119B,P120B_1,P120B_2,P120B_3,P120B_4,P120B_5,P120B_5_OT,P121B,P121B_SI_1,P121B_SI_2,P122B,P123B,P123B_SI,P124B,P124B_SI,P124B_NO,P124B_NO_O,P125B,P126B,P126B_SI_1,P126B_SI_2,P127B,P128B,P128B_SI,P129B,P130B,P131B_1,P131B_2,P131B_3,P131B_4,P131B_5,P131B_6,P131B_7,P132B_1,P132B_2,P133B,P133B_SI,P134B,P134B_S1_1,P134B_S1_2,P134B_S1_3,P134B_S1_4,P134B_S1_5,P134B_S1_6,P134B_S1_7,P134B_S1_O,P134B_S2_1,P134B_S2_2,P134B_S2_3,P135B,P135B_S_1,P135B_S_2,P135B_S_3,P135B_S_4,P135B_S_5,P135B_SI_5,P136B,P136B_S_1,P136B_S_2,P136B_S_3,P136B_S_4,P136B_S_4O,NIV_MOD,GES_DEP,AREA_CENSO,CODGEO,CODOOII,MSE_EBR,MSE_ST,P5_FORMA,P5_DETALLE,P5_7_CANT,P5_7_LPPAL,P5_7_DIST,P5_7_TERRP,P111A,P111A_S_1,P111A_S_2,P111A_S_3,P111A_S_4,P111A_S_5,P111A_S_5O,P114A_1_CP,P114A_2_CP,P115A,P115A_S_1,P115A_S_2,P115A_S_3,P115A_S_4,P115A_S_5,P115A_S_5O,P118A_1,P118A_2,P118A_3,P118A_4,P118A_5,P118A_6,P118A_7,P118A_7_OT,P120A_S_1,P120A_S_2,P120A_S_3,P120A_S_4,P120A_S_5,P120A_S_5O,P121A_SI,P131B,P131B_S_1M,P131B_S_1C,P131B_S_2M,P131B_S_2C,P131B_S_3M,P131B_S_3C,P131B_S_4M,P131B_S_4C,P132B_3,P132B_4,P133B_1,P133B_2,P133B_3,P133B_4,P134B_1,P134B_2,P134B_3,P134B_4,P134B_5,P134B_6,P134B_7,P135B_1,P135B_2,P136B_SI,P137B,P137B_S1_1,P137B_S1_2,P137B_S1_3,P137B_S1_4,P137B_S1_5,P137B_S1_6,P137B_S1_7,P137B_S1_O,P137B_S2_1,P137B_S2_2,P137B_S2_3,P138B,P138B_S_1,P138B_S_2,P138B_S_3,P138B_S_4,P138B_S_5,P138B_SI_5,P139B,P139B_S_1,P139B_S_2,P139B_S_3,P139B_S_4,P139B_S_4O
count,2029.00,2029.00,2029.00,2029,2029,2029,1917,2026,255,62,45,10,97,40,40,2027,1565,168.00,14,2027,1169,125,98,429,366,651,2027,901,346,236,108,75,266,0.00,1310,416,1960,35,13,576,42,6,13,13,2029,376,759,867,280,46,46,1829,2027,117.00,121.00,1310,856,243,464,153,72,75,2028,2027,1728,1310,321,408,236,275,16,16,660,98.00,1792,1435,1577,1185,1337,1280,835,43,43,2027,1864,1865,1875,1691,1275.00,1414,1386,635,1128,494,861,41,42,1805,1052,1358,856,2023,2025,1897.00,2026,1702.00,614,1197,652,381,751,1069,755,41,37,1441,1665,828,1001,1004,31,17,31,2024,2026,1525.00,2027,1221,999,442,1042,59,60,2027,1979,1979,1980,2028,1957,2028,1877.00,154.00,7,2028,1896,471.00,2028,2027,2028,1931,2027,2028,428,299,753,424,564,29,29,1166,699,786,717,1054,36,91,32,6,24,79,4,3,24,48,161,1310,116,242,164,128,13,13,1886,312,132,54,18,19,2029,2029,2029.00,2029.00,2029.00,708.00,13.00,718.00,718,7.00,15,5.00,10,717,205,438,529,116,50,50,112.00,84.00,718,485,179,302,118,51,51,280,84,229,115,106,408,27,28,246,256,170,221,9,9,87.00,718,262,268,133,127,122,121,43,39,464,298,554,409,273,329,326,186,573,94,383,28,28,501,331,526,310,30,66,28,5,20,48,3,3,25,50,96,718,96,156,113,85,3,3,718,220,116,38,13,13
unique,NaN,NaN,NaN,2,1429,173,759,2,2,1,1,1,1,1,18,2,2,NaN,13,2,1,1,1,1,1,1,2,1,1,1,1,1,1,NaN,2,2,3,1,1,1,1,1,1,11,2,1,1,1,1,1,25,2,2,NaN,NaN,2,1,1,1,1,1,39,11,2,11,2,1,1,1,1,1,16,2,NaN,1,1,1,1,1,1,1,1,29,2,2,2,2,2,NaN,1,1,1,1,1,1,1,33,1,1,1,1,2,2,NaN,2,NaN,1,1,1,1,1,1,2,1,23,1,1,1,1,1,1,1,25,2,2,NaN,2,1,1,1,1,1,51,2,2,2,2,2,2,2,NaN,NaN,7,2,2,NaN,183,2,2,2,2,2,1,1,1,1,1,1,22,391,291,2,2,2,1,1,1,1,1,1,1,3,1,1,1,2,1,1,1,1,1,6,2,1,1,1,1,17,2,6,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,2,NaN,2,2,1,1,1,1,1,33,NaN,NaN,2,1,1,1,1,1,29,1,1,1,1,1,1,1,26,1,1,1,1,1,8,NaN,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,24,319,236,2,2,1,1,1,1,1,1,1,3,1,1,1,2,1,1,1,1,1,3,2,1,1,1,1,12
top,NaN,NaN,NaN,3AP,SAN FRANCISCO DE ASIS,CERRO COLORADO,AREQUIPA,NO,SI,X,X,X,X,X,CLASES VIRTUALES,SI,SI,NaN,NO APROBARON ALGUN CRITERIO DE EVALUACION,SI,X,X,X,X,X,X,SI,X,X,X,X,X,X,NaN,NO,SI,SI,X,X,X,X,X,X,POSTA,SI,X,X,X,X,X,ESCUELA DE PADRES,SI,NO,NaN,NaN,SI,X,X,X,X,X,VACUNACION,SI,SI,8,SI,X,X,X,X,X,INVOLUCRAMIENTO CON AUTORIDADES ALIADAS,NO,NaN,X,X,X,X,X,X,X,X,AUXILIAR DE EDUCACION,SI,SI,SI,SI,SI,NaN,X,X,X,X,X,X,X,CHARLAS,X,X,X,X,SI,SI,NaN,SI,NaN,X,X,X,X,X,X,X,X,NINGUNO,X,X,X,X,X,X,X,PROGRAMAS PREVENTIVOS,SI,SI,NaN,SI,X,X,X,X,X,IE UNIDOCENTE,SI,SI,SI,SI,SI,SI,SI,NaN,NaN,NO HAY CASOS,SI,NO,NaN,//,SI,SI,SI,SI,SI,X,X,X,X,X,X,POLICIA ESCOLAR,X,X,SI,SI,NO,X,X,X,X,X,X,X,PSICOLOGA UGEL,X,X,X,NO,X,X,X,X,X,PLANIFICACION,SI,X,X,X,X,UGEL,B0,B4,NaN,NaN,NaN,NaN,NaN,NaN,1 JER-Jornada Escolar Regular,NaN,SI,NaN,SI,SI,X,X,X,X,X,ESCUELA DE PADRES,NaN,NaN,SI,X,X,X,X,X,VACUNAS,X,X,X,X,X,X,X,ESCALA,X,X,X,X,X,PRIVADO,NaN,SI,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,NINGUNO,X,0,SI,NO,X,X,X,X,X,X,X,PAGINA WEB,X,X,X,NO,X,X,X,X,X,ATENCION ACTIVA CONCIENTE,NO,X,X,X,X,UGEL
freq,NaN,NaN,NaN,1311,5,255,351,1787,225,62,45,10,97,40,9,1560,1401,NaN,2,1975,1169,125,98,429,366,651,2011,901,346,236,108,75,266,NaN,894,368,1091,35,13,576,42,6,13,2,1250,376,759,867,280,46,16,1226,1382,NaN,NaN,964,856,243,464,153,72,17,1137,1200,583,658,321,408,236,275,16,1,562,NaN,1792,1435,1577,1185,1337,1280,835,43,4,1865,1826,1689,1669,1272,NaN,1414,1386,635,1128,494,861,41,3,1805,1052,1358,856,1588,1893,NaN,1699,NaN,614,1197,652,381,751,1069,754,41,7,1441,1665,828,1001,1004,31,17,2,1762,1523,NaN,1864,1221,999,442,1042,59,5,1978,1966,1910,1715,1952,1686,1874,NaN,NaN,1,1886,1433,NaN,1565,1143,1930,1541,1915,1756,428,299,753,424,564,29,4,511,259,711,522,840,36,91,32,6,24,79,4,1,24,48,161,929,116,242,164,128,13,8,976,312,132,54,18,3,1311,976,NaN,NaN,NaN,NaN,NaN,NaN,547,NaN,8,NaN,5,639,205,438,529,116,50,17,NaN,NaN,549,485,179,302,118,51,10,280,84,229,115,106,408,27,2,246,256,170,221,9,2,NaN,518,262,268,133,127,122,121,43,39,464,298,554,409,273,329,326,186,573,94,383,28,4,12,18,406,175,30,66,28,5,20,48,3,1,25,50,96,468,96,156,113,85,3,1,393,220,116,38,13,2
mean,1040324.69,0.00,341165.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.01,2.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.76,NaN,2.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.49,2.91,NaN,NaN,NaN,3.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.26,40239.63,40003.51,1.24,3.77,1.31,NaN,22.71,NaN,14.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.04,3.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,620472.17,0.00,331636.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.15,3.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.82,NaN,2.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.43,1.29,NaN,NaN,NaN,6.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.44,210.00,3.09,0.44,1.30,0.82,NaN,36.81,NaN,20.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.09,3.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,216689.00,0.00,1924.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,1.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,40101.00,40001.00,1.00,2.00,1.00,NaN,0.00,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,314278.00,0.00,64252.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,1.00,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,40104.00,40001.00,1.00,3.00,1.00,NaN,0.00,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1031673.00,0.00,72134.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,3.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,40117.00,40002.00,1.00,4.00,1.00,NaN,0.00,NaN,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1515311.00,0.00,650266.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.00,NaN,3.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,4.00,NaN,NaN,NaN,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,40401.00,40005.00,1.00,5.00,1.00,NaN,29.50,NaN,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,3051109.00,0.00,998926.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.00,22.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.00,NaN,31.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,502.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.00,5.00,NaN,NaN,NaN,88.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,40811.00,40010.00,3.00,5.00,9.00,NaN,100.00,NaN,50.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.00,21.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##### Errores tipográficos encontrado

In [16]:
#print value count per district using format district: number
for district, count in df_p_s['DISTRITO'].value_counts().items():
    print(f"{district}: {count}")

CERRO COLORADO: 255
AREQUIPA: 167
PAUCARPATA: 130
MAJES: 112
CAYMA: 87
SOCABAYA: 77
MARIANO MELGAR: 70
JOSE LUIS BUSTAMANTE Y RIVERO: 65
ALTO SELVA ALEGRE: 63
LA JOYA: 60
MIRAFLORES: 51
YURA: 48
JACOBO HUNTER: 42
SACHACA: 37
MOLLENDO: 25
YANAHUARA: 24
TIABAYA: 23
APLAO: 22
MARIANO NICOLAS VALCARCEL: 17
CERCADO: 16
URACA: 15
SAMUEL PASTOR: 15
CAMANA: 14
COCACHACRA: 14
CAYLLOMA: 14
PAMPAMARCA: 13
HUAYNACOTAS: 13
ORCOPAMPA: 13
CHARACATO: 13
CAYARANI: 13
UCHUMAYO: 13
YANAQUIHUA: 12
CHUQUIBAMBA: 12
PUYCA: 12
OCOÑA: 12
ACARI: 11
TISCO: 10
HUNTER: 10
TORO: 9
DEAN VALDIVIA: 9
CHACHAS: 9
CHIGUATA: 9
CHOCO: 8
COTAHUASI: 8
VIRACO: 8
NICOLAS DE PIEROLA: 8
CHAPARRA: 8
SAN JUAN DE TARUCANI: 8
QUICACHA: 8
ATICO: 8
ALCA: 7
CHIVAY: 7
TAPAY: 7
LLUTA: 7
CHALA: 7
RIO GRANDE: 6
SALAMANCA: 6
CHICHAS: 6
SANTA RITA DE SIGUAS: 6
SANTA ISABEL DE SIGUAS: 6
POLOBAYA: 6
VITOR: 6
HUANUHUANU: 6
ANDARAY: 5
SAYLA: 5
ISLAY: 5
TIPAN: 5
PUNTA DE BOMBON: 5
CAHUACHO: 5
PAMPACOLCA: 5
ANDAGUA: 5
CALLALLI: 5
YANQUE: 5
TOMEPAMPA: 4
SAN JUAN DE SIGUAS: 4
SAN ANTONIO DE CHUCA: 4
CAMANÁ: 4
HUANCA: 4
CABANACONDE: 4
COPORAQUE: 4
MARISCAL CACERES: 4
ATIQUIPA: 4
SIBAYO: 3
MACHAGUAY: 3
YARABAMBA: 3
QUECHUALLA: 3
RÍO GRANDE: 3
IRAY: 3
JOSE MARIA QUIMPER: 3
POCSI: 3
MOLLEBAYA: 3
AYO: 3
ACHOMA: 3
CARAVELI: 3
HUAMBO: 3
JAQUI: 3
CHARCANA: 3
HUANCARQUI: 2
CHILCAYMARCA: 2
YAUCA: 2
TUTI: 2
PUNTA DE BOMBÓN: 2
UÑON: 2
TAURIA: 2
LOMAS: 2
ICHUPAMPA: 2
SABANDIA: 2
MADRIGAL: 2
MACA: 2
LARI: 2
MACHAHUAY: 2
CHÁPARRA: 2
QUILCA: 2
BELLA UNIÓN: 2
BELLA UNION: 2
JOSE LUIS BUSTAMENTE Y RIVERO: 2
CALLALI: 1
CERRO COLRADO: 1
JOSE LUIS BUSTAMANTE Y RIV ERO: 1
MARIANO MELGA: 1
MEJÍA: 1
ANDAGUS: 1
ALTO SELVA AELGRE: 1
QUEQUEÑA: 1
CERROCOLORADO: 1
JACOBO DICKSON HUNTER: 1
ORCOPMPA: 1
JOSSE LUIS BUSTAMANTE Y RIVERO: 1
JOSÉ LUIS BUSTAMANTE Y RIVERO: 1
JOSÉ LUIS BUSTAMATE Y RIVERO: 1
AMPLIACION SOCABAYA: 1
CABANCONDE: 1
CERRO C0LORADO: 1
JOSE LUIS BUSTAMANTE Y RIBERO: 1
SANTARITA DE SIGUAS: 1
MARIANO MELGARX: 1
ORCOPAPA: 1
JA JOYA: 1
ALTO SELA ALEGRE: 1
NICOLÁS DE PIÉROLA: 1
VICTOR: 1
ACARÍ: 1
CALLE COLO SIN NUMERO: 1
MARIANOMELGAR: 1
PEDREGAL: 1
MARIANO NICOLAS VARCALCEL: 1
VÍTOR: 1
JACOBO  HUNTER: 1
ALTOS SELVA ALEGRE: 1
SABANDÍA: 1
MARIANO NICOLÁS VALCÁRCEL: 1
SAMUEL PASTOR LA PAMPA: 1
SELVA ALEGRE: 1
AREUIPA: 1
JOSE LUIS BUSTAMANTE Y RIVERP: 1
PUACARPATA: 1
MEJIA: 1
SOCABAY: 1
SACABAYA: 1
MUNDO ECOLOGICO: 1
ALTO  SELVA  ALEGRE: 1
JOSE LUIS BUSTAMATE Y RIVERO: 1
CERCADO DE AREQUIPA: 1
DEAN VALDIVA: 1
PAURCAPATA: 1
COCCHACRA: 1
CHILCAIMARCA: 1
PAUCARAPATA: 1
JULIO ERNESTO PORTUGAL ESCOBEDO: 1
CARAVELÍ: 1
ALTO SELVA LEGRE: 1
ALTO SELVA ALGRE: 1
CHARACAO: 1

In [ ]:
from difflib import get_close_matches

CORRECCIONES = {
    "JOSE LUIS BUSTAMENTE Y RIVERO":        "JOSE LUIS BUSTAMANTE Y RIVERO",
    "JOSE LUIS BUSTAMANTE Y RIV ERO":       "JOSE LUIS BUSTAMANTE Y RIVERO",
    "JOSSE LUIS BUSTAMANTE Y RIVERO":       "JOSE LUIS BUSTAMANTE Y RIVERO",
    "JOSÉ LUIS BUSTAMANTE Y RIVERO":        "JOSE LUIS BUSTAMANTE Y RIVERO",
    "JOSÉ LUIS BUSTAMATE Y RIVERO":         "JOSE LUIS BUSTAMANTE Y RIVERO",
    "JOSE LUIS BUSTAMANTE Y RIBERO":        "JOSE LUIS BUSTAMANTE Y RIVERO",
    "JOSE LUIS BUSTAMENTE Y RIVERO":        "JOSE LUIS BUSTAMANTE Y RIVERO",
    "JOSE LUIS BUSTAMANTE Y RIVERP":        "JOSE LUIS BUSTAMANTE Y RIVERO",
    "JOSE LUIS BUSTAMATE Y RIVERO":         "JOSE LUIS BUSTAMANTE Y RIVERO",
    "JOSE LUIS BUSTAMENTE Y RIVERO":        "JOSE LUIS BUSTAMANTE Y RIVERO",
    "JOSE LUIS BUSTAMANTE Y RIVERO":        "JOSE LUIS BUSTAMANTE Y RIVERO",  # canónico
    "JOSE LUIS BUSTAMENTE Y RIVERO":        "JOSE LUIS BUSTAMANTE Y RIVERO",

    # CERRO COLORADO
    "CERRO COLRADO":                        "CERRO COLORADO",
    "CERROCOLORADO":                        "CERRO COLORADO",
    "CERRO C0LORADO":                       "CERRO COLORADO",   # cero en lugar de O

    # ALTO SELVA ALEGRE
    "ALTO SELVA AELGRE":                    "ALTO SELVA ALEGRE",
    "ALTO SELVA LEGRE":                     "ALTO SELVA ALEGRE",
    "ALTO SELVA ALGRE":                     "ALTO SELVA ALEGRE",
    "ALTO  SELVA  ALEGRE":                  "ALTO SELVA ALEGRE",  # espacios dobles
    "ALTOS SELVA ALEGRE":                   "ALTO SELVA ALEGRE",
    "ALTO SELA ALEGRE":                     "ALTO SELVA ALEGRE",
    "SELVA ALEGRE":                         "ALTO SELVA ALEGRE",

    # MARIANO MELGAR
    "MARIANO MELGA":                        "MARIANO MELGAR",
    "MARIANO MELGARX":                      "MARIANO MELGAR",
    "MARIANOMELGAR":                        "MARIANO MELGAR",

    # MARIANO NICOLAS VALCARCEL
    "MARIANO NICOLAS VARCALCEL":            "MARIANO NICOLAS VALCARCEL",
    "MARIANO NICOLÁS VALCÁRCEL":            "MARIANO NICOLAS VALCARCEL",

    # JACOBO HUNTER
    "JACOBO DICKSON HUNTER":                "JACOBO HUNTER",
    "JACOBO  HUNTER":                       "JACOBO HUNTER",   # doble espacio

    # PAUCARPATA
    "PUACARPATA":                           "PAUCARPATA",
    "PAURCAPATA":                           "PAUCARPATA",
    "PAUCARAPATA":                          "PAUCARPATA",

    # ORCOPAMPA
    "ORCOPMPA":                             "ORCOPAMPA",
    "ORCOPAPA":                             "ORCOPAMPA",

    # SOCABAYA
    "SOCABAY":                              "SOCABAYA",
    "AMPLIACION SOCABAYA":                  "SOCABAYA",
    "SACABAYA":                             "SOCABAYA",

    # CALLALLI
    "CALLALI":                              "CALLALLI",

    # CABANACONDE
    "CABANCONDE":                           "CABANACONDE",

    # AREQUIPA
    "AREUIPA":                              "AREQUIPA",
    "CERCADO DE AREQUIPA":                  "CERCADO",

    # CARAVELI
    "CARAVELÍ":                             "CARAVELI",

    # CHAPARRA
    "CHÁPARRA":                             "CHAPARRA",

    # LA JOYA
    "JA JOYA":                              "LA JOYA",

    # NICOLAS DE PIEROLA
    "NICOLÁS DE PIÉROLA":                   "NICOLAS DE PIEROLA",

    # VICTOR / VITOR
    "VICTOR":                               "VITOR",
    "VÍTOR":                                "VITOR",

    # SABANDIA
    "SABANDÍA":                             "SABANDIA",

    # SAMUEL PASTOR
    "SAMUEL PASTOR LA PAMPA":               "SAMUEL PASTOR",

    # ACARI
    "ACARÍ":                                "ACARI",

    # MEJIA
    "MEJÍA":                                "MEJIA",

    # BELLA UNION (normalizar tilde)
    "BELLA UNIÓN":                          "BELLA UNION",

    # CAMANA (normalizar tilde)
    "CAMANÁ":                               "CAMANA",

    # RIO GRANDE (normalizar tilde)
    "RÍO GRANDE":                           "RIO GRANDE",

    # PUNTA DE BOMBON (normalizar tilde)
    "PUNTA DE BOMBÓN":                      "PUNTA DE BOMBON",

    # CHILCAIMARCA
    "CHILCAIMARCA":                         "CHILCAYMARCA",

    # DEAN VALDIVIA
    "DEAN VALDIVA":                         "DEAN VALDIVIA",

    # COCACHACRA
    "COCCHACRA":                            "COCACHACRA",

    # ANDAGUA
    "ANDAGUS":                              "ANDAGUA",

    # MACHAHUAY / MACHAGUAY (misma localidad)
    "MACHAHUAY":                            "MACHAGUAY",

    # CHARACATO
    "CHARACAO":                             "CHARACATO",

    # Entradas sin correspondencia geográfica reconocida
    # Se dejan mapeadas a valores más descriptivos o se normalizan
    "CALLE COLO SIN NUMERO":               "SIN DATOS",
    "MUNDO ECOLOGICO":                     "SIN DATOS",
    "JULIO ERNESTO PORTUGAL ESCOBEDO":     "SIN DATOS",
    "PEDREGAL":                            "MAJES",          # Pedregal es la ciudad capital del distrito de Majes
}


# ─────────────────────────────────────────────
# 2. LISTA CANÓNICA DE DISTRITOS
#    (los que tienen conteo >= 5 en el dataset original)
# ─────────────────────────────────────────────
DISTRITOS_CANONICOS = [
    "CERRO COLORADO", "AREQUIPA", "PAUCARPATA", "MAJES", "CAYMA",
    "SOCABAYA", "MARIANO MELGAR", "JOSE LUIS BUSTAMANTE Y RIVERO",
    "ALTO SELVA ALEGRE", "LA JOYA", "MIRAFLORES", "YURA",
    "JACOBO HUNTER", "SACHACA", "MOLLENDO", "YANAHUARA", "TIABAYA",
    "APLAO", "MARIANO NICOLAS VALCARCEL", "CERCADO", "URACA",
    "SAMUEL PASTOR", "CAMANA", "COCACHACRA", "CAYLLOMA", "PAMPAMARCA",
    "HUAYNACOTAS", "ORCOPAMPA", "CHARACATO", "CAYARANI", "UCHUMAYO",
    "YANAQUIHUA", "CHUQUIBAMBA", "PUYCA", "OCOÑA", "ACARI", "TISCO",
    "HUNTER", "TORO", "DEAN VALDIVIA", "CHACHAS", "CHIGUATA", "CHOCO",
    "COTAHUASI", "VIRACO", "NICOLAS DE PIEROLA", "CHAPARRA",
    "SAN JUAN DE TARUCANI", "QUICACHA", "ATICO", "ALCA", "CHIVAY",
    "TAPAY", "LLUTA", "CHALA", "RIO GRANDE", "SALAMANCA", "CHICHAS",
    "SANTA RITA DE SIGUAS", "SANTA ISABEL DE SIGUAS", "POLOBAYA",
    "VITOR", "HUANUHUANU", "ANDARAY", "SAYLA", "ISLAY", "TIPAN",
    "PUNTA DE BOMBON", "CAHUACHO", "PAMPACOLCA", "ANDAGUA", "CALLALLI",
    "YANQUE", "TOMEPAMPA", "SAN JUAN DE SIGUAS", "SAN ANTONIO DE CHUCA",
    "HUANCA", "CABANACONDE", "COPORAQUE", "MARISCAL CACERES", "ATIQUIPA",
    "SIBAYO", "MACHAGUAY", "YARABAMBA", "QUECHUALLA", "IRAY",
    "JOSE MARIA QUIMPER", "POCSI", "MOLLEBAYA", "AYO", "ACHOMA",
    "CARAVELI", "HUAMBO", "JAQUI", "CHARCANA", "HUANCARQUI",
    "CHILCAYMARCA", "YAUCA", "TUTI", "UÑON", "TAURIA", "LOMAS",
    "ICHUPAMPA", "SABANDIA", "MADRIGAL", "MACA", "LARI", "QUILCA",
    "BELLA UNION", "MEJIA", "QUEQUEÑA",
]


def curar_distrito(nombre: str) -> str:
    """
    Aplica correcciones en dos pasos:
      1. Mapa explícito (cubre todos los casos conocidos).
      2. Fuzzy-matching contra la lista canónica (fallback).
    """
    if pd.isna(nombre):
        return nombre

    # Normalizar espacios extras
    nombre_norm = " ".join(str(nombre).upper().split())

    # Paso 1: corrección explícita
    if nombre_norm in CORRECCIONES:
        return CORRECCIONES[nombre_norm]

    # Paso 2: si ya está en la lista canónica, no tocar
    if nombre_norm in DISTRITOS_CANONICOS:
        return nombre_norm

    # Paso 3: fuzzy-matching (umbral 0.82 para evitar falsos positivos)
    matches = get_close_matches(nombre_norm, DISTRITOS_CANONICOS, n=1, cutoff=0.82)
    if matches:
        return matches[0]

    # Sin match → devolver tal como está (para revisión manual)
    return nombre_norm


# ─────────────────────────────────────────────
# 3. APLICAR AL DATAFRAME
# ─────────────────────────────────────────────
# df_p_s["DISTRITO"] = df_p_s["DISTRITO"].apply(curar_distrito)

# ─────────────────────────────────────────────
# 4. VERIFICACIÓN: mostrar cambios realizados
# ─────────────────────────────────────────────
def mostrar_cambios(df: pd.DataFrame, columna: str = "DISTRITO") -> pd.DataFrame:
    """Devuelve un DataFrame con las filas que fueron modificadas."""
    original = df[columna].str.upper().str.strip()
    corregida = df[columna]
    mask = original != corregida
    return pd.DataFrame({
        "indice": df.index[mask],
        "original": original[mask].values,
        "corregido": corregida[mask].values,
    })


# ─────────────────────────────────────────────
# USO COMPLETO (descomentar para ejecutar):
# ─────────────────────────────────────────────
df_p_s["DISTRITO"] = df_p_s["DISTRITO"].apply(curar_distrito)
cambios = mostrar_cambios(df_p_s)
print(f"\nTotal de filas corregidas: {len(cambios)}")
print(cambios.to_string(index=False))
print("\nConteo final:")
for d, c in df_p_s["DISTRITO"].value_counts().items():
    print(f"  {d}: {c}")

Total de filas corregidas: 0
Empty DataFrame
Columns: [indice, original, corregido]
Index: []

Conteo final:
  CERRO COLORADO: 258
  AREQUIPA: 168
  PAUCARPATA: 133
  MAJES: 113
  CAYMA: 87
  SOCABAYA: 80
  JOSE LUIS BUSTAMANTE Y RIVERO: 74
  MARIANO MELGAR: 73
  ALTO SELVA ALEGRE: 70
  LA JOYA: 61
  MIRAFLORES: 51
  YURA: 48
  JACOBO HUNTER: 44
  SACHACA: 37
  MOLLENDO: 25
  YANAHUARA: 24
  TIABAYA: 23
  APLAO: 22
  MARIANO NICOLAS VALCARCEL: 19
  CAMANA: 18
  CERCADO: 17
  SAMUEL PASTOR: 16
  URACA: 15
  ORCOPAMPA: 15
  COCACHACRA: 15
  CHARACATO: 14
  CAYLLOMA: 14
  PAMPAMARCA: 13
  HUAYNACOTAS: 13
  CAYARANI: 13
  UCHUMAYO: 13
  YANAQUIHUA: 12
  CHUQUIBAMBA: 12
  PUYCA: 12
  ACARI: 12
  OCOÑA: 12
  DEAN VALDIVIA: 10
  TISCO: 10
  CHAPARRA: 10
  HUNTER: 10
  RIO GRANDE: 9
  TORO: 9
  CHACHAS: 9
  NICOLAS DE PIEROLA: 9
  CHIGUATA: 9
  CHOCO: 8
  COTAHUASI: 8
  VIRACO: 8
  VITOR: 8
  SAN JUAN DE TARUCANI: 8
  QUICACHA: 8
  ATICO: 8
  ALCA: 7
  CHIVAY: 7
  SANTA RITA DE SIGUAS: 7
  PUNTA DE BOMBON: 7
  TAPAY: 7
  LLUTA: 7
  CHALA: 7
  CALLALLI: 6
  SALAMANCA: 6
  CHICHAS: 6
  ANDAGUA: 6
  SANTA ISABEL DE SIGUAS: 6
  POLOBAYA: 6
  HUANUHUANU: 6
  ANDARAY: 5
  SAYLA: 5
  ISLAY: 5
  MACHAGUAY: 5
  TIPAN: 5
  CAHUACHO: 5
  PAMPACOLCA: 5
  YANQUE: 5
  CABANACONDE: 5
  TOMEPAMPA: 4
  SAN JUAN DE SIGUAS: 4
  SAN ANTONIO DE CHUCA: 4
  HUANCA: 4
  COPORAQUE: 4
  MARISCAL CACERES: 4
  CARAVELI: 4
  ATIQUIPA: 4
  BELLA UNION: 4
  SIBAYO: 3
  YARABAMBA: 3
  CHILCAYMARCA: 3
  QUECHUALLA: 3
  IRAY: 3
  JOSE MARIA QUIMPER: 3
  POCSI: 3
  MOLLEBAYA: 3
  AYO: 3
  ACHOMA: 3
  SABANDIA: 3
  HUAMBO: 3
  JAQUI: 3
  SIN DATOS: 3
  CHARCANA: 3
  HUANCARQUI: 2
  YAUCA: 2
  TUTI: 2
  MEJIA: 2
  UÑON: 2
  TAURIA: 2
  LOMAS: 2
  ICHUPAMPA: 2
  MADRIGAL: 2
  MACA: 2
  LARI: 2
  QUILCA: 2
  QUEQUEÑA: 1

##### Column cleaned

In [34]:
df_p_s['DISTRITO'].value_counts().to_frame().T

DISTRITO,CERRO COLORADO,AREQUIPA,PAUCARPATA,MAJES,CAYMA,SOCABAYA,JOSE LUIS BUSTAMANTE Y RIVERO,MARIANO MELGAR,ALTO SELVA ALEGRE,LA JOYA,MIRAFLORES,YURA,JACOBO HUNTER,SACHACA,MOLLENDO,YANAHUARA,TIABAYA,APLAO,MARIANO NICOLAS VALCARCEL,CAMANA,CERCADO,SAMUEL PASTOR,URACA,ORCOPAMPA,COCACHACRA,CHARACATO,CAYLLOMA,PAMPAMARCA,HUAYNACOTAS,CAYARANI,UCHUMAYO,YANAQUIHUA,CHUQUIBAMBA,PUYCA,ACARI,OCOÑA,DEAN VALDIVIA,TISCO,CHAPARRA,HUNTER,RIO GRANDE,TORO,CHACHAS,NICOLAS DE PIEROLA,CHIGUATA,CHOCO,COTAHUASI,VIRACO,VITOR,SAN JUAN DE TARUCANI,QUICACHA,ATICO,ALCA,CHIVAY,SANTA RITA DE SIGUAS,PUNTA DE BOMBON,TAPAY,LLUTA,CHALA,CALLALLI,SALAMANCA,CHICHAS,ANDAGUA,SANTA ISABEL DE SIGUAS,POLOBAYA,HUANUHUANU,ANDARAY,SAYLA,ISLAY,MACHAGUAY,TIPAN,CAHUACHO,PAMPACOLCA,YANQUE,CABANACONDE,TOMEPAMPA,SAN JUAN DE SIGUAS,SAN ANTONIO DE CHUCA,HUANCA,COPORAQUE,MARISCAL CACERES,CARAVELI,ATIQUIPA,BELLA UNION,SIBAYO,YARABAMBA,CHILCAYMARCA,QUECHUALLA,IRAY,JOSE MARIA QUIMPER,POCSI,MOLLEBAYA,AYO,ACHOMA,SABANDIA,HUAMBO,JAQUI,CHARCANA,HUANCARQUI,YAUCA,TUTI,MEJIA,UÑON,TAURIA,LOMAS,ICHUPAMPA,MADRIGAL,MACA,LARI,QUILCA,QUEQUEÑA
count,258,168,133,113,87,80,77,73,70,61,51,48,44,37,25,24,23,22,19,18,17,16,15,15,15,14,14,13,13,13,13,12,12,12,12,12,10,10,10,10,9,9,9,9,9,8,8,8,8,8,8,8,7,7,7,7,7,7,7,6,6,6,6,6,6,6,5,5,5,5,5,5,5,5,5,4,4,4,4,4,4,4,4,4,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,2,2,2,2,2,2,2,2,2,2,2,1

In [22]:
print(f"Número de distritos distintos: {df_p_s['DISTRITO'].nunique()}")

Número de distritos distintos: 112

In [33]:
df_p_s[df_p_s['DISTRITO'] == 'SIN DATOS']

Empty DataFrame
Columns: [COD_MOD, ANEXO, CODLOCAL, NROCED, CEN_EDU, DISTRITO, LOCALIDAD, P104A, P105A, P105A_S_1, P105A_S_2, P105A_S_3, P105A_S_4, P105A_S_5, P105A_S_5O, P106A, P107A, P107A_NO, P107A_NO_O, P108A, P109A_1, P109A_2, P109A_3, P109A_4, P109A_5, P109A_6, P110A, P111A_1, P111A_2, P111A_3, P111A_4, P111A_5, P111A_6, P111A_5_OT, P112A, P112A_SI, P113A, P113A_S_1, P113A_S_2, P113A_S_3, P113A_S_4, P113A_S_5, P113A_S_6, P113A_S_6O, P114A, P114A_S_1, P114A_S_2, P114A_S_3, P114A_S_4, P114A_S_5, P114A_S_5O, P116A, P117A, P117A_1_CP, P117A_2_CP, P118A, P118A_S_1, P118A_S_2, P118A_S_3, P118A_S_4, P118A_S_5, P118A_S_5O, P119A, P120A, P121A, P122A, P122A_S_1, P122A_S_2, P122A_S_3, P122A_S_4, P122A_S_5, P122A_S_5O, P123A, P123A_SI, P102B_1, P102B_2, P102B_3, P102B_4, P102B_5, P102B_6, P102B_7, P102B_8, P102B_8_OT, P103B, P103B_SI_1, P103B_SI_2, P105B, P106B, P106B_SI, P109B_1, P109B_2, P109B_3, P109B_4, P109B_5, P109B_6, P109B_7, P109B_7_OT, P110B_1, P110B_2, P110B_3, ...]
Index: []

##### Assigning their correct District

In [32]:
#mostrar colegio con cod_mod 894584
df_p_s.iloc[895:896]['CEN_EDU']
#ponerle valor en distrito 'JOSE LUIS BUSTAMANTE Y RIVERO'
df_p_s.loc[df_p_s['DISTRITO'] == 'SIN DATOS', 'DISTRITO'] = 'JOSE LUIS BUSTAMANTE Y RIVERO'

In [36]:
df_p_s.describe(include='all')

# Duplicados
# print('Duplicados df_a:', df_a.duplicated().sum())
# print('Duplicados df_b:', df_b.duplicated().sum())

,COD_MOD,ANEXO,CODLOCAL,NROCED,CEN_EDU,DISTRITO,LOCALIDAD,P104A,P105A,P105A_S_1,P105A_S_2,P105A_S_3,P105A_S_4,P105A_S_5,P105A_S_5O,P106A,P107A,P107A_NO,P107A_NO_O,P108A,P109A_1,P109A_2,P109A_3,P109A_4,P109A_5,P109A_6,P110A,P111A_1,P111A_2,P111A_3,P111A_4,P111A_5,P111A_6,P111A_5_OT,P112A,P112A_SI,P113A,P113A_S_1,P113A_S_2,P113A_S_3,P113A_S_4,P113A_S_5,P113A_S_6,P113A_S_6O,P114A,P114A_S_1,P114A_S_2,P114A_S_3,P114A_S_4,P114A_S_5,P114A_S_5O,P116A,P117A,P117A_1_CP,P117A_2_CP,P118A,P118A_S_1,P118A_S_2,P118A_S_3,P118A_S_4,P118A_S_5,P118A_S_5O,P119A,P120A,P121A,P122A,P122A_S_1,P122A_S_2,P122A_S_3,P122A_S_4,P122A_S_5,P122A_S_5O,P123A,P123A_SI,P102B_1,P102B_2,P102B_3,P102B_4,P102B_5,P102B_6,P102B_7,P102B_8,P102B_8_OT,P103B,P103B_SI_1,P103B_SI_2,P105B,P106B,P106B_SI,P109B_1,P109B_2,P109B_3,P109B_4,P109B_5,P109B_6,P109B_7,P109B_7_OT,P110B_1,P110B_2,P110B_3,P110B_4,P111B,P112B,P112B_SI,P113B,P113B_SI,P114B_1,P114B_2,P114B_3,P114B_4,P114B_5,P114B_6,P114B_7,P114B_8,P114B_8_OT,P115B_1,P115B_2,P115B_3,P115B_4,P115B_5,P115B_6,P115B_7,P115B_6_OT,P117B,P118B,P118B_SI,P119B,P120B_1,P120B_2,P120B_3,P120B_4,P120B_5,P120B_5_OT,P121B,P121B_SI_1,P121B_SI_2,P122B,P123B,P123B_SI,P124B,P124B_SI,P124B_NO,P124B_NO_O,P125B,P126B,P126B_SI_1,P126B_SI_2,P127B,P128B,P128B_SI,P129B,P130B,P131B_1,P131B_2,P131B_3,P131B_4,P131B_5,P131B_6,P131B_7,P132B_1,P132B_2,P133B,P133B_SI,P134B,P134B_S1_1,P134B_S1_2,P134B_S1_3,P134B_S1_4,P134B_S1_5,P134B_S1_6,P134B_S1_7,P134B_S1_O,P134B_S2_1,P134B_S2_2,P134B_S2_3,P135B,P135B_S_1,P135B_S_2,P135B_S_3,P135B_S_4,P135B_S_5,P135B_SI_5,P136B,P136B_S_1,P136B_S_2,P136B_S_3,P136B_S_4,P136B_S_4O,NIV_MOD,GES_DEP,AREA_CENSO,CODGEO,CODOOII,MSE_EBR,MSE_ST,P5_FORMA,P5_DETALLE,P5_7_CANT,P5_7_LPPAL,P5_7_DIST,P5_7_TERRP,P111A,P111A_S_1,P111A_S_2,P111A_S_3,P111A_S_4,P111A_S_5,P111A_S_5O,P114A_1_CP,P114A_2_CP,P115A,P115A_S_1,P115A_S_2,P115A_S_3,P115A_S_4,P115A_S_5,P115A_S_5O,P118A_1,P118A_2,P118A_3,P118A_4,P118A_5,P118A_6,P118A_7,P118A_7_OT,P120A_S_1,P120A_S_2,P120A_S_3,P120A_S_4,P120A_S_5,P120A_S_5O,P121A_SI,P131B,P131B_S_1M,P131B_S_1C,P131B_S_2M,P131B_S_2C,P131B_S_3M,P131B_S_3C,P131B_S_4M,P131B_S_4C,P132B_3,P132B_4,P133B_1,P133B_2,P133B_3,P133B_4,P134B_1,P134B_2,P134B_3,P134B_4,P134B_5,P134B_6,P134B_7,P135B_1,P135B_2,P136B_SI,P137B,P137B_S1_1,P137B_S1_2,P137B_S1_3,P137B_S1_4,P137B_S1_5,P137B_S1_6,P137B_S1_7,P137B_S1_O,P137B_S2_1,P137B_S2_2,P137B_S2_3,P138B,P138B_S_1,P138B_S_2,P138B_S_3,P138B_S_4,P138B_S_5,P138B_SI_5,P139B,P139B_S_1,P139B_S_2,P139B_S_3,P139B_S_4,P139B_S_4O
count,2029.00,2029.00,2029.00,2029,2029,2029,1917,2026,255,62,45,10,97,40,40,2027,1565,168.00,14,2027,1169,125,98,429,366,651,2027,901,346,236,108,75,266,0.00,1310,416,1960,35,13,576,42,6,13,13,2029,376,759,867,280,46,46,1829,2027,117.00,121.00,1310,856,243,464,153,72,75,2028,2027,1728,1310,321,408,236,275,16,16,660,98.00,1792,1435,1577,1185,1337,1280,835,43,43,2027,1864,1865,1875,1691,1275.00,1414,1386,635,1128,494,861,41,42,1805,1052,1358,856,2023,2025,1897.00,2026,1702.00,614,1197,652,381,751,1069,755,41,37,1441,1665,828,1001,1004,31,17,31,2024,2026,1525.00,2027,1221,999,442,1042,59,60,2027,1979,1979,1980,2028,1957,2028,1877.00,154.00,7,2028,1896,471.00,2028,2027,2028,1931,2027,2028,428,299,753,424,564,29,29,1166,699,786,717,1054,36,91,32,6,24,79,4,3,24,48,161,1310,116,242,164,128,13,13,1886,312,132,54,18,19,2029,2029,2029.00,2029.00,2029.00,708.00,13.00,718.00,718,7.00,15,5.00,10,717,205,438,529,116,50,50,112.00,84.00,718,485,179,302,118,51,51,280,84,229,115,106,408,27,28,246,256,170,221,9,9,87.00,718,262,268,133,127,122,121,43,39,464,298,554,409,273,329,326,186,573,94,383,28,28,501,331,526,310,30,66,28,5,20,48,3,3,25,50,96,718,96,156,113,85,3,3,718,220,116,38,13,13
unique,NaN,NaN,NaN,2,1429,111,759,2,2,1,1,1,1,1,18,2,2,NaN,13,2,1,1,1,1,1,1,2,1,1,1,1,1,1,NaN,2,2,3,1,1,1,1,1,1,11,2,1,1,1,1,1,25,2,2,NaN,NaN,2,1,1,1,1,1,39,11,2,11,2,1,1,1,1,1,16,2,NaN,1,1,1,1,1,1,1,1,29,2,2,2,2,2,NaN,1,1,1,1,1,1,1,33,1,1,1,1,2,2,NaN,2,NaN,1,1,1,1,1,1,2,1,23,1,1,1,1,1,1,1,25,2,2,NaN,2,1,1,1,1,1,51,2,2,2,2,2,2,2,NaN,NaN,7,2,2,NaN,183,2,2,2,2,2,1,1,1,1,1,1,22,391,291,2,2,2,1,1,1,1,1,1,1,3,1,1,1,2,1,1,1,1,1,6,2,1,1,1,1,17,2,6,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,2,NaN,2,2,1,1,1,1,1,33,NaN,NaN,2,1,1,1,1,1,29,1,1,1,1,1,1,1,26,1,1,1,1,1,8,NaN,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,24,319,236,2,2,1,1,1,1,1,1,1,3,1,1,1,2,1,1,1,1,1,3,2,1,1,1,1,12
top,NaN,NaN,NaN,3AP,SAN FRANCISCO DE ASIS,CERRO COLORADO,AREQUIPA,NO,SI,X,X,X,X,X,CLASES VIRTUALES,SI,SI,NaN,NO APROBARON ALGUN CRITERIO DE EVALUACION,SI,X,X,X,X,X,X,SI,X,X,X,X,X,X,NaN,NO,SI,SI,X,X,X,X,X,X,POSTA,SI,X,X,X,X,X,ESCUELA DE PADRES,SI,NO,NaN,NaN,SI,X,X,X,X,X,VACUNACION,SI,SI,8,SI,X,X,X,X,X,INVOLUCRAMIENTO CON AUTORIDADES ALIADAS,NO,NaN,X,X,X,X,X,X,X,X,AUXILIAR DE EDUCACION,SI,SI,SI,SI,SI,NaN,X,X,X,X,X,X,X,CHARLAS,X,X,X,X,SI,SI,NaN,SI,NaN,X,X,X,X,X,X,X,X,NINGUNO,X,X,X,X,X,X,X,PROGRAMAS PREVENTIVOS,SI,SI,NaN,SI,X,X,X,X,X,IE UNIDOCENTE,SI,SI,SI,SI,SI,SI,SI,NaN,NaN,NO HAY CASOS,SI,NO,NaN,//,SI,SI,SI,SI,SI,X,X,X,X,X,X,POLICIA ESCOLAR,X,X,SI,SI,NO,X,X,X,X,X,X,X,PSICOLOGA UGEL,X,X,X,NO,X,X,X,X,X,PLANIFICACION,SI,X,X,X,X,UGEL,B0,B4,NaN,NaN,NaN,NaN,NaN,NaN,1 JER-Jornada Escolar Regular,NaN,SI,NaN,SI,SI,X,X,X,X,X,ESCUELA DE PADRES,NaN,NaN,SI,X,X,X,X,X,VACUNAS,X,X,X,X,X,X,X,ESCALA,X,X,X,X,X,PRIVADO,NaN,SI,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,NINGUNO,X,0,SI,NO,X,X,X,X,X,X,X,PAGINA WEB,X,X,X,NO,X,X,X,X,X,ATENCION ACTIVA CONCIENTE,NO,X,X,X,X,UGEL
freq,NaN,NaN,NaN,1311,5,258,351,1787,225,62,45,10,97,40,9,1560,1401,NaN,2,1975,1169,125,98,429,366,651,2011,901,346,236,108,75,266,NaN,894,368,1091,35,13,576,42,6,13,2,1250,376,759,867,280,46,16,1226,1382,NaN,NaN,964,856,243,464,153,72,17,1137,1200,583,658,321,408,236,275,16,1,562,NaN,1792,1435,1577,1185,1337,1280,835,43,4,1865,1826,1689,1669,1272,NaN,1414,1386,635,1128,494,861,41,3,1805,1052,1358,856,1588,1893,NaN,1699,NaN,614,1197,652,381,751,1069,754,41,7,1441,1665,828,1001,1004,31,17,2,1762,1523,NaN,1864,1221,999,442,1042,59,5,1978,1966,1910,1715,1952,1686,1874,NaN,NaN,1,1886,1433,NaN,1565,1143,1930,1541,1915,1756,428,299,753,424,564,29,4,511,259,711,522,840,36,91,32,6,24,79,4,1,24,48,161,929,116,242,164,128,13,8,976,312,132,54,18,3,1311,976,NaN,NaN,NaN,NaN,NaN,NaN,547,NaN,8,NaN,5,639,205,438,529,116,50,17,NaN,NaN,549,485,179,302,118,51,10,280,84,229,115,106,408,27,2,246,256,170,221,9,2,NaN,518,262,268,133,127,122,121,43,39,464,298,554,409,273,329,326,186,573,94,383,28,4,12,18,406,175,30,66,28,5,20,48,3,1,25,50,96,468,96,156,113,85,3,1,393,220,116,38,13,2
mean,1040324.69,0.00,341165.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.01,2.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.76,NaN,2.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.49,2.91,NaN,NaN,NaN,3.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.26,40239.63,40003.51,1.24,3.77,1.31,NaN,22.71,NaN,14.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.04,3.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,620472.17,0.00,331636.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.15,3.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.82,NaN,2.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.43,1.29,NaN,NaN,NaN,6.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.44,210.00,3.09,0.44,1.30,0.82,NaN,36.81,NaN,20.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.09,3.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,216689.00,0.00,1924.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,1.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,40101.00,40001.00,1.00,2.00,1.00,NaN,0.00,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,314278.00,0.00,64252.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,1.00,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,40104.00,40001.00,1.00,3.00,1.00,NaN,0.00,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1031673.00,0.00,72134.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,3.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,40117.00,40002.00,1.00,4.00,1.00,NaN,0.00,NaN,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1515311.00,0.00,650266.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.00,NaN,3.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,4.00,NaN,NaN,NaN,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,40401.00,40005.00,1.00,5.00,1.00,NaN,29.50,NaN,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,3051109.00,0.00,998926.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.00,22.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.00,NaN,31.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,502.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.00,5.00,NaN,NaN,NaN,88.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,40811.00,40010.00,3.00,5.00,9.00,NaN,100.00,NaN,50.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.00,21.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Filtrado

In [37]:
#solo sacar las columnas cod_mod, cenn_edu, distrito, localidad
df_p_s_solo_localizacion = df_p_s[['COD_MOD', 'CEN_EDU', 'DISTRITO', 'LOCALIDAD']]

### Output

In [39]:
df_p_s_solo_localizacion.to_csv(PATH_OUT_FULL, index=False)
print(f'Exportado: {PATH_OUT_FULL} ({df_p_s_solo_localizacion.shape[0]} filas totales)')

Exportado: ../../data/cleaned/districts.csv (2029 filas totales)